config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :word

  has_many :results
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  has_many :results, dependent: :destroy
  has_many :words, through: :results
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :word
  belongs_to :answer
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save ->{self.email = email.downcase}

  has_many :activities, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :results, through: :lessons

  has_many :following_relationships, class_name: "Relationship",
    foreign_key: "follower_id", dependent: :delete_all
  has_many :followers_relationships, class_name: "Relationship",
    foreign_key: "followed_id", dependent: :delete_all

  has_many :following, through: :following_relationships, source: :followed
  has_many :followers, through: :followers_relationships, source: :follower

  has_secure_password

  validates :email,
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
    presence: true, length: {maximum: Settings.user.maximum_characters},
    uniqueness: {case_sensitive: false}
  validates :password, allow_nil: true,
    length: {minimum: Settings.user.minimum_characters}
  validates :name, presence: true,
    length: {maximum: Settings.user.maximum_characters}

  def User.digest string
    cost = if ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
    BCrypt::Password.create string, cost: cost
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update_attributes remember_digest: nil
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :results
  has_many :answers
  has_many :lessons, through: :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == Settings.session.number ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = t "controllers.sessions.create.flash_danger"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate page: params[:page], per_page: Settings.user.per_page
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "controllers.users.create.flash_success",
        name: @user.name
      redirect_to @user
    else
      render :new
    end
  end

  def show
    if User.exists? params[:id]
      @user = User.find params[:id]
    else
      flash[:danger] = t "controllers.users.show.flash_danger"
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "#{Settings.user.gravatar_url}#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t(".website"), "#" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".home"), "#" %></li>
      <li><%= link_to t(".help"), "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <%= link_to t(".website"), "#", id: "logo" %>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), "#" %></li>
        <li><%= link_to t(".help"), "#" %></li>
        <% if logged_in? %>
          <li><%= link_to t(".all_users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
              <%= t ".account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".sign_up"), signup_path %></li>
          <li><%= link_to t(".log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t ".title" %></title>
  <%= stylesheet_link_tag "application",
    media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container body-content">
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
    <%= yield %>  
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".error_message" %> <%= @user.errors.count %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-4 row">
    <section class="user_info center jumbotron">
    </section>    
  </div>
  <div class="col-md-8 container-fluid">
    <div class="row", id="user-menu">
      <form>
        <button type="submit" class="btn btn-default col-md-4">
          <%= t ".btn_words" %>
        </button>
        <button type="submit" class="btn btn-default col-md-4">
          <%= t ".btn_lessons" %>
        </button>
      </form>
    </div>
    <hr/>
    <div class="row", id="user-word-list">
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<h1><%= t ".h1index" %></h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<h1><%= t ".signup" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name, t(".name") %>
      <%= f.text_field :name %>

      <%= f.label :email, t(".email") %>
      <%= f.email_field :email %>

      <%= f.label :password, t(".password") %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, t(".confirmation") %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit t(".btn_submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= render @user %>
      </h1>
    </section>
  </aside>
</div>